### ISSUE TITLE
Command h2r-graphics: Variable List: Allow accept variables

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-h2r-graphics#60]
Allow the function `h2r-graphics: Variable List` to also accept values ​​from variables and expressions. It will then allow you to dynamically enter the sheet number (from a variable/expression) and select a row (from a variable/expression).

Companion: 3.1.1
OS: Win10

**Comment by iamjohnbarker** [comment]
Adding this to the next version!

**Comment by CDMalwitz** [comment]
Did the ability to set the row number with a companion variable or expression been added?  It doesn't look like this part of the issue was completed.

H2R_Graphics: Variable List - Select row by Number.   The Row Number field can only be a raw value (e.g, 1,2,3,4,5,...).  Cannot enter a companion variable ($) or expression in the field.

Does another issue/enhancement need to be added?

**Comment by iamjohnbarker** [comment]
I'm on version `v3.5.0+7604-main-ebe71398` and it's working on my end to add a variable

<img width="739" alt="Image" src="https://github.com/user-attachments/assets/7a0784a7-bc2e-4ed1-880a-aca1f5503076" />

What version are you running?

**Comment by CDMalwitz** [comment]
I am referring to the row# that shows when you select “Number” in the **Next/Previous/Number** field.

**Comment by iamjohnbarker** [comment]
Good catch - adding that now to the next beta

**Comment by CDMalwitz** [comment]
Thanks for the quick response!  H2R Graphics, along with its Companion module, make it much easier to do titles and lower-thirds for our Sunday streaming services.  Both our great products.
